GET https://examensarb.herokuapp.com/

###
GET https://examensarb.herokuapp.com/authors

###
DELETE https://examensarb.herokuapp.com/authors/delete/63b46b4418c2479777e744b5

###
POST https://examensarb.herokuapp.com/authors/new
content-type: application/json

{
    "name": "Bret Easton Ellis",
    "rating": 5,
    "categories": ["Horror", "Contemperary"]
}
###
POST https://examensarb.herokuapp.com/items/new
content-type: application/json

{
    "title": "American Psycho",
    "author": "63b55ca0d73776bc29ce64d1",
    "number": "666",
    "image": "http://images.com/jaws.jpg",
    "description": "About a killer in New York",
    "categories": ["Horror", "Contemperary"],
    "rating": 4,
    "home": true,
    "lender": "none"
}

###
POST https://examensarb.herokuapp.com/users/new
content-type: application/json

{
    "firstName": "Jag",
    "lastName": "Callesson",
    "password": "666",
    "email": "jag@sf.com"
}

###
POST https://examensarb.herokuapp.com/users/login
content-type: application/json

{
    "password": "666",
    "email": "jag@sf.com"
}

### Users ########################################################
GET http://localhost:3000/users

###
DELETE http://localhost:3000/users/delete/63b5dd732931f5f42266e36

###
POST http://localhost:3000/users/new
content-type: application/json

{
    "firstName": "Lena",
    "lastName": "Nilsson",
    "password": "666",
    "email": "lena@sf.com"
}

###
PUT http://localhost:3000/users/63b5c608a6c710a39767985b
content-type: application/json

{
    "firstName": "Petter",
    "lastName": "Callesson",
    "password": "666",
    "email": "mail@mail.com"
}

###
POST http://localhost:3000/users/login
content-type: application/json

{
    "password": "666",
    "email": "lena@sf.com"
}

### Auth ########################################################
GET http://localhost:3000/users/63c54c8b03ba9b32e3ea486c
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzU0YzhiMDNiYTliMzJlM2VhNDg2YyIsImVtYWlsIjoicGV0dGVyIiwiaWF0IjoxNjczODg5NzUwfQ.ytQhwv--wqyiRFLyIgCcQ3O53dtFQijP9Ywvb0TJUBQ

### ITEMS ########################################################
GET http://localhost:3000/items/63b5de4b91fa8908df0f75c7

### 
GET http://localhost:3000/items

###

GET http://localhost:3000/items/Book

###
DELETE http://localhost:3000/items/63be864fc439f4cdfa240137

###
POST http://localhost:3000/items/new
content-type: application/json

{
    "title": "Test",
    "author": "Test",
    "number": "666",
    "image": "https://res.cloudinary.com/dajj8zghh/image/upload/v1673460759/img/mxhj4akj3bq00nxcvrsq.png",
    "description": "TestTestTest",
    "rating": 2,
    "category": "Book",
    "sub": "Horror",
    "home": true
}

###
PUT http://localhost:3000/items/63bd7d03fc7d2a57cd3a5e18
content-type: application/json

{
    "title": "Minuscule vol. 1",
    "author": "?",
    "number": "666",
    "image": "https://res.cloudinary.com/dajj8zghh/image/upload/v1673362635/img/rtjxqmxavlkyczvbdlfa.jpg",
    "description": "About a Bug in France",
    "category": "DVD",
    "sub": "Animated",
    "rating": 4,
    "home": true,
    "lender": "none"
}

###
PATCH http://localhost:3000/items/63b6c4771d945f0c4527dceb
content-type: application/json

{
    "home": false,
    "lender": "Rustan Jävel"
}
### Authors ########################################################
GET http://localhost:3000/authors/63b46af43c3423f139107d4f

###
GET http://localhost:3000/authors

###
DELETE http://localhost:3000/authors/delete/63b5a42c7909af0168e686c6

###
POST http://localhost:3000/authors/new
content-type: application/json

{
    "name": "Bret Eason Ellis",
    "rating": 5,
    "categories": ["Horror", "Contemperary"]
}

###
PUT http://localhost:3000/authors/63b46af43c3423f139107d4
content-type: application/json

{
    "name": "Peter Benchley",
    "rating": 3,
    "categories": ["Horror", "Drama"]
}


### CATEGORIES #####################################################################
GET http://localhost:3000/categories/
###
POST http://localhost:3000/categories/new
content-type: application/json

{
    "name": "Magazine",
    "subs": [      
        "Horror",
        "Contemperary",
        "Thriller",
        "Fantasy",
        "Mystery",
        "War",
        "Drama",
        "Sience Fiction",
        "Ducumentary",
        "Music"
    ]
}

###
PUT http://localhost:3000/categories/63bd54b79a14f18eebba7ea1
content-type: application/json

{
    "name": "Book",
        "subs": [      
        "Horror",
        "Contemperary",
        "Thriller",
        "Fantasy",
        "Mystery",
        "War",
        "Drama",
        "Sience Fiction",
        "Ducumentary",
        "Music",
        "Biography"
    ]
}

###
GET http://localhost:3000/images